---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: devops-toolkit-staging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: ofluxdev
  interval: 30s
  targetNamespace: ofluxstage
  values:
    image:
      tag: 2.9.9
    ingress:
      host: ofluxdev.192.168.49.2.nip.io
